"""
ui/app_protocol.py — AppProtocol 接口族

面板通过协议与 App 交互，不依赖具体 App 类。
测试时注入 Mock 实现对应协议即可。
"""
from typing import Protocol, Optional


class SidebarProtocol(Protocol):
    """HistorySidebar 依赖的 App 接口。"""
    @property
    def root(self) -> "tk.Tk": ...
    @property
    def cfg(self) -> dict: ...
    @property
    def sel_id(self) -> Optional[int]: ...
    @property
    def cur_path(self) -> Optional[str]: ...
    @property
    def _cur_bytes(self) -> Optional[bytes]: ...
    @property
    def _sidebar_w(self) -> int: ...
    @property
    def MAX_NICK_LEN(self) -> int: ...
    def _log(self, msg: str) -> None: ...
    def _st(self, msg: str, k: str = "ok") -> None: ...
    def _refresh_hist(self, load_all: bool = False) -> None: ...
    def _refresh_tag_stats(self) -> None: ...
    def _load_entry(self, e: dict) -> None: ...
    def _gen(self, event=None) -> None: ...
    def _reset_view(self) -> None: ...
    def _export(self) -> None: ...
    def _open_viewer(self) -> None: ...
    def _set_cmp_from_entry(self, e: dict) -> None: ...
    def _display_title(self, e: dict) -> str: ...


class MainContentProtocol(Protocol):
    """MainContent 依赖的 App 接口。"""
    @property
    def root(self) -> "tk.Tk": ...
    @property
    def cfg(self) -> dict: ...
    @property
    def cur_path(self) -> Optional[str]: ...
    @property
    def _cur_bytes(self) -> Optional[bytes]: ...
    def _log(self, msg: str) -> None: ...
    def _st(self, msg: str, k: str = "ok") -> None: ...
    def _gen(self, event=None) -> None: ...
    def _gen_variants(self) -> None: ...
    def _load_entry(self, e: dict) -> None: ...
    def _open_viewer(self) -> None: ...
    def _open_wizard(self) -> None: ...
    def _open_paid_wizard(self) -> None: ...
    def _open_phrase_panel(self) -> None: ...
    def _open_prompt_wizard(self) -> None: ...
    def _switch_to_variant_tab(self) -> None: ...
    def _switch_to_queue_tab(self) -> None: ...
    def _save(self) -> None: ...
    def _copy_path(self) -> None: ...
    def _clr_log(self) -> None: ...
    def _update_char_count(self) -> None: ...
    def _set_cmp_from_entry(self, e: dict) -> None: ...
    def _display_title(self, e: dict) -> str: ...


# Legacy alias for backward compatibility
AppProtocol = MainContentProtocol
